### ISSUE TITLE
Error while running minimal-example.conf 

### ISSUE THREAD

**Issue by kirankxyz** [SparkTC/spark-bench#122]
Hi,
Iam getting error when i run this command after setting environment variables. I have also added the spark-args and master in conf file also.. Error i get is this:

[drmhwt@vm00002662 spark-bench_2.1.1_0.2.2-RELEASE]$ ./bin/spark-bench.sh ./examples/from-docs/minimal-example.conf
I'M HERE::: /home/drmhwt/spark-bench_2.1.1_0.2.2-RELEASE/lib/spark-bench-launch-2.1.1_0.2.2-RELEASE.jar
 *** SPARK-SUBMIT: [/usr/hdp/2.5.0.0-1245/spark/bin/spark-submit, --class, com.ibm.sparktc.sparkbench.cli.CLIKickoff, --master, yarn-client, /home/drmhwt/spark-bench_2.1.1_0.2.2-RELEASE/lib/spark-bench-2.1.1_0.2.2-RELEASE.jar, /tmp/spark-bench-6445914711687433332.conf]
Exception in thread "main" java.lang.NoSuchMethodError: scala.Predef$.$conforms()Lscala/Predef$$less$colon$less;
        at com.ibm.sparktc.sparkbench.utils.TypesafeAccessories$.configToMapStringAny(TypesafeAccessories.scala:46)
        at com.ibm.sparktc.sparkbench.cli.Configurator$$anonfun$7.apply(Configurator.scala:46)
        at com.ibm.sparktc.sparkbench.cli.Configurator$$anonfun$7.apply(Configurator.scala:46)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)

Please guide , where i am going wrong...
Thanks in advance

**Comment by ecurtin** [comment]
This almost certain a Scala version incompatibility. Spark-Bench uses Scala 2.11 (specifically 2.11.8) so if your version of Spark was built with Scala 2.10 this will be incompatible. You can see the version of Scala used by spark by opening spark-shell on your cluster. The Scala version will be printed out like this:

```
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /___/ .__/\_,_/_/ /_/\_\   version 2.1.1
      /_/

Using Scala version 2.11.8 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_144)
```

**Comment by kirankxyz** [comment]
Yes..scala version i use is 2.10.. i will work on that.. thank you.. :)

**Comment by ecurtin** [comment]
Cool! I'm gonna close this issue since we worked out what the problem was. Feel free to reopen or open a new one if you have more questions :)
