### ISSUE TITLE
Shutdown hook called before final status was reported

### ISSUE THREAD

**Issue by gongshijun** [SparkTC/spark-bench#127]
Follow is th logs.

1. slaver1
```
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/data/hadoop-data/tmp/nm-local-dir/usercache/hadoop/filecache/13/__spark_libs__4891032027996517596.zip/slf4j-log4j12-1.7.16.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/opt/hadoop-2.7.4/share/hadoop/common/lib/slf4j-log4j12-1.7.10.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
17/11/08 14:35:25 INFO util.SignalUtils: Registered signal handler for TERM
17/11/08 14:35:25 INFO util.SignalUtils: Registered signal handler for HUP
17/11/08 14:35:25 INFO util.SignalUtils: Registered signal handler for INT
17/11/08 14:35:26 INFO yarn.ApplicationMaster: Preparing Local resources
17/11/08 14:35:27 INFO yarn.ApplicationMaster: ApplicationAttemptId: appattempt_1510118383275_0002_000002
17/11/08 14:35:27 INFO spark.SecurityManager: Changing view acls to: hadoop
17/11/08 14:35:27 INFO spark.SecurityManager: Changing modify acls to: hadoop
17/11/08 14:35:27 INFO spark.SecurityManager: Changing view acls groups to: 
17/11/08 14:35:27 INFO spark.SecurityManager: Changing modify acls groups to: 
17/11/08 14:35:27 INFO spark.SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(hadoop); groups with view permissions: Set(); users  with modify permissions: Set(hadoop); groups with modify permissions: Set()
17/11/08 14:35:27 INFO yarn.ApplicationMaster: Waiting for Spark driver to be reachable.
17/11/08 14:35:27 ERROR yarn.ApplicationMaster: Failed to connect to driver at 192.168.98.129:34255, retrying ...
17/11/08 14:35:27 ERROR yarn.ApplicationMaster: Failed to connect to driver at 192.168.98.129:34255, retrying ...
17/11/08 14:35:27 ERROR yarn.ApplicationMaster: Failed to connect to driver at 192.168.98.129:34255, retrying ...
17/11/08 14:35:27 ERROR yarn.ApplicationMaster: Failed to connect to driver at 192.168.98.129:34255, retrying ...
17/11/08 14:35:27 ERROR yarn.ApplicationMaster: RECEIVED SIGNAL TERM
17/11/08 14:35:27 INFO yarn.ApplicationMaster: Final app status: UNDEFINED, exitCode: 16, (reason: Shutdown hook called before final status was reported.)
17/11/08 14:35:27 INFO yarn.ApplicationMaster: Unregistering ApplicationMaster with UNDEFINED (diag message: Shutdown hook called before final status was reported.)
17/11/08 14:35:27 INFO yarn.ApplicationMaster: Deleting staging directory hdfs://master-virtual-machine:9000/user/hadoop/.sparkStaging/application_1510118383275_0002
17/11/08 14:35:27 INFO util.ShutdownHookManager: Shutdown hook called
17/11/08 14:35:27 ERROR yarn.ApplicationMaster: Uncaught exception: 
org.apache.spark.SparkException: Failed to connect to driver!
	at org.apache.spark.deploy.yarn.ApplicationMaster.waitForSparkDriver(ApplicationMaster.scala:577)
	at org.apache.spark.deploy.yarn.ApplicationMaster.runExecutorLauncher(ApplicationMaster.scala:433)
	at org.apache.spark.deploy.yarn.ApplicationMaster.run(ApplicationMaster.scala:256)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anonfun$main$1.apply$mcV$sp(ApplicationMaster.scala:764)
	at org.apache.spark.deploy.SparkHadoopUtil$$anon$2.run(SparkHadoopUtil.scala:67)
	at org.apache.spark.deploy.SparkHadoopUtil$$anon$2.run(SparkHadoopUtil.scala:66)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1698)
	at org.apache.spark.deploy.SparkHadoopUtil.runAsSparkUser(SparkHadoopUtil.scala:66)
	at org.apache.spark.deploy.yarn.ApplicationMaster$.main(ApplicationMaster.scala:762)
	at org.apache.spark.deploy.yarn.ExecutorLauncher$.main(ApplicationMaster.scala:785)
	at org.apache.spark.deploy.yarn.ExecutorLauncher.main(ApplicationMaster.scala)
```

2. slaver2
```
 Showing 4096 bytes. Click here for full log

)
17/11/08 14:35:20 INFO yarn.ApplicationMaster: 
===============================================================================
YARN executor launch context:
  env:
    CLASSPATH -> {{PWD}}<CPS>{{PWD}}/__spark_conf__<CPS>{{PWD}}/__spark_libs__/*<CPS>$HADOOP_CONF_DIR<CPS>$HADOOP_COMMON_HOME/share/hadoop/common/*<CPS>$HADOOP_COMMON_HOME/share/hadoop/common/lib/*<CPS>$HADOOP_HDFS_HOME/share/hadoop/hdfs/*<CPS>$HADOOP_HDFS_HOME/share/hadoop/hdfs/lib/*<CPS>$HADOOP_YARN_HOME/share/hadoop/yarn/*<CPS>$HADOOP_YARN_HOME/share/hadoop/yarn/lib/*<CPS>$HADOOP_MAPRED_HOME/share/hadoop/mapreduce/*<CPS>$HADOOP_MAPRED_HOME/share/hadoop/mapreduce/lib/*
    SPARK_YARN_STAGING_DIR -> hdfs://master-virtual-machine:9000/user/hadoop/.sparkStaging/application_1510118383275_0002
    SPARK_USER -> hadoop
    SPARK_YARN_MODE -> true

  command:
    {{JAVA_HOME}}/bin/java \ 
      -server \ 
      -Xmx1024m \ 
      -Djava.io.tmpdir={{PWD}}/tmp \ 
      '-Dspark.driver.port=34255' \ 
      -Dspark.yarn.app.container.log.dir=<LOG_DIR> \ 
      -XX:OnOutOfMemoryError='kill %p' \ 
      org.apache.spark.executor.CoarseGrainedExecutorBackend \ 
      --driver-url \ 
      spark://CoarseGrainedScheduler@192.168.98.129:34255 \ 
      --executor-id \ 
      <executorId> \ 
      --hostname \ 
      <hostname> \ 
      --cores \ 
      1 \ 
      --app-id \ 
      application_1510118383275_0002 \ 
      --user-class-path \ 
      file:$PWD/__app__.jar \ 
      1><LOG_DIR>/stdout \ 
      2><LOG_DIR>/stderr

  resources:
    __spark_libs__ -> resource { scheme: "hdfs" host: "master-virtual-machine" port: 9000 file: "/user/hadoop/.sparkStaging/application_1510118383275_0002/__spark_libs__4891032027996517596.zip" } size: 208179347 timestamp: 1510122865315 type: ARCHIVE visibility: PRIVATE
    __spark_conf__ -> resource { scheme: "hdfs" host: "master-virtual-machine" port: 9000 file: "/user/hadoop/.sparkStaging/application_1510118383275_0002/__spark_conf__.zip" } size: 86607 timestamp: 1510122866017 type: ARCHIVE visibility: PRIVATE

===============================================================================
17/11/08 14:35:20 INFO client.RMProxy: Connecting to ResourceManager at master-virtual-machine/192.168.98.129:8030
17/11/08 14:35:20 INFO yarn.YarnRMClient: Registering the ApplicationMaster
17/11/08 14:35:20 INFO yarn.YarnAllocator: Will request 2 executor container(s), each with 1 core(s) and 1408 MB memory (including 384 MB of overhead)
17/11/08 14:35:20 INFO yarn.YarnAllocator: Submitted 2 unlocalized container requests.
17/11/08 14:35:20 INFO yarn.ApplicationMaster: Started progress reporter thread with (heartbeat : 3000, initial allocation : 200) intervals
17/11/08 14:35:21 INFO impl.AMRMClientImpl: Received new token for : gongshijun-virtual-machine:34525
17/11/08 14:35:21 INFO yarn.YarnAllocator: Launching container container_1510118383275_0002_01_000002 on host gongshijun-virtual-machine for executor with ID 1
17/11/08 14:35:21 INFO yarn.YarnAllocator: Received 1 containers from YARN, launching executors on 1 of them.
17/11/08 14:35:21 INFO impl.ContainerManagementProtocolProxy: yarn.client.max-cached-nodemanagers-proxies : 0
17/11/08 14:35:21 INFO impl.ContainerManagementProtocolProxy: Opening proxy : gongshijun-virtual-machine:34525
17/11/08 14:35:21 INFO impl.AMRMClientImpl: Received new token for : gsjt1:45373
17/11/08 14:35:21 INFO yarn.YarnAllocator: Launching container container_1510118383275_0002_01_000003 on host gsjt1 for executor with ID 2
17/11/08 14:35:21 INFO yarn.YarnAllocator: Received 1 containers from YARN, launching executors on 1 of them.
17/11/08 14:35:21 INFO impl.ContainerManagementProtocolProxy: yarn.client.max-cached-nodemanagers-proxies : 0
17/11/08 14:35:21 INFO impl.ContainerManagementProtocolProxy: Opening proxy : gsjt1:45373
17/11/08 14:35:21 ERROR yarn.ApplicationMaster: RECEIVED SIGNAL TERM
17/11/08 14:35:21 INFO yarn.ApplicationMaster: Final app status: UNDEFINED, exitCode: 16, (reason: Shutdown hook called before final status was reported.)
17/11/08 14:35:21 INFO util.ShutdownHookManager: Shutdown hook called
```
all logs:
``` 
Application application_1510118383275_0002 failed 2 times due to AM Container for appattempt_1510118383275_0002_000002 exited with exitCode: -103
For more detailed output, check application tracking page:http://master-virtual-machine:8088/cluster/app/application_1510118383275_0002Then, click on links to logs of each attempt.
Diagnostics: Container [pid=28408,containerID=container_1510118383275_0002_02_000001] is running beyond virtual memory limits. Current usage: 291.9 MB of 1 GB physical memory used; 2.2 GB of 2.1 GB virtual memory used. Killing container.
Dump of the process-tree for container_1510118383275_0002_02_000001 :
|- PID PPID PGRPID SESSID CMD_NAME USER_MODE_TIME(MILLIS) SYSTEM_TIME(MILLIS) VMEM_USAGE(BYTES) RSSMEM_USAGE(PAGES) FULL_CMD_LINE
|- 28413 28408 28408 28408 (java) 547 129 2341548032 73983 /usr/lib/jvm/java-1.8.0-openjdk-amd64/bin/java -server -Xmx512m -Djava.io.tmpdir=/data/hadoop-data/tmp/nm-local-dir/usercache/hadoop/appcache/application_1510118383275_0002/container_1510118383275_0002_02_000001/tmp -Dspark.yarn.app.container.log.dir=/opt/hadoop-2.7.4/logs/userlogs/application_1510118383275_0002/container_1510118383275_0002_02_000001 org.apache.spark.deploy.yarn.ExecutorLauncher --arg 192.168.98.129:34255 --properties-file /data/hadoop-data/tmp/nm-local-dir/usercache/hadoop/appcache/application_1510118383275_0002/container_1510118383275_0002_02_000001/__spark_conf__/__spark_conf__.properties
|- 28408 28407 28408 28408 (bash) 0 0 20094976 755 /bin/bash -c /usr/lib/jvm/java-1.8.0-openjdk-amd64/bin/java -server -Xmx512m -Djava.io.tmpdir=/data/hadoop-data/tmp/nm-local-dir/usercache/hadoop/appcache/application_1510118383275_0002/container_1510118383275_0002_02_000001/tmp -Dspark.yarn.app.container.log.dir=/opt/hadoop-2.7.4/logs/userlogs/application_1510118383275_0002/container_1510118383275_0002_02_000001 org.apache.spark.deploy.yarn.ExecutorLauncher --arg '192.168.98.129:34255' --properties-file /data/hadoop-data/tmp/nm-local-dir/usercache/hadoop/appcache/application_1510118383275_0002/container_1510118383275_0002_02_000001/__spark_conf__/__spark_conf__.properties 1> /opt/hadoop-2.7.4/logs/userlogs/application_1510118383275_0002/container_1510118383275_0002_02_000001/stdout 2> /opt/hadoop-2.7.4/logs/userlogs/application_1510118383275_0002/container_1510118383275_0002_02_000001/stderr
Container killed on request. Exit code is 143
Container exited with a non-zero exit code 143
Failing this attempt. Failing the application. 
```
Follow is my conf.
```
spark-bench = {
  spark-home = "/opt/spark-2.2.0-bin-hadoop2.7"
  spark-submit-config = [{
    spark-args = {
      master = "yarn"
    }
    workload-suites = [
      {
        descr = "Generating data for the benchmarks to use"
        parallel = false
        repeat = 1
        benchmark-output = "./mytest/output/kmeansdg"
        workloads = [
          {
            name = "data-generation-kmeans"
            output = "hdfs://master-virtual-machine:9000/data/kmeans/kmeans-data.parquet"
            rows = 1000000
            cols = 14
          },
          {
            name = "data-generation-logistic-regression"
            output = "hdfs://master-virtual-machine:9000/data/lr/logisric-regression.parquet"
            rows = 1000000
            cols = 14
          }
       ]
     }
   ]
  }]
}
~ 
```

**Comment by ecurtin** [comment]
Hi @gongshijun! Thank you for your patience, and thank you as well for using Spark-Bench :)

Based on your log output, I'm not sure this is a Spark-Bench issue. A couple questions:

1. In your Spark configuration file (outside of Spark-Bench) are you using cluster mode? If so, there is a known bug with cluster mode that is currently being worked on. (issue #107) Using master = yarn with client mode should work correctly though. I see you are not specifying `deploy-mode` in your spark-bench configuration file, but it might be getting set for you by default Spark configuration. Just something to check and rule out!

2. Are you able to run other Spark applications through spark-submit on this cluster?

3. Are your permissions set correctly on this cluster? Based on some of the lines in your stack trace it looks like there _might_ be auth problems.

**Comment by gongshijun** [comment]
Hi @ecurtin! Than you for you suggestion. Then I found out that it was my problem.

**Comment by lu-liu-rft** [comment]
Hi I have encountered this issue when running spark script on AWS glue, here is the question: https://stackoverflow.com/questions/66473039/aws-glue-job-failed-with-error-error-client-application-diagnostics-message-uCan someone take a look please?
