### ISSUE TITLE
User unable to use Graph Data Generator

### ISSUE THREAD

**Issue by ecurtin** [SparkTC/spark-bench#137]
_Pulled from conversation with @JDetwiler15_ in #82 

### Spark-Bench Version
_Unknown_

### Spark Version on Your Cluster
Spark 2.2.1

### Scala Version on Your Spark Cluster
_Uknown_

### Your Exact Configuration File (with system details anonymized)
_Unknown_

### Relevant Stack Trace (If Applicable)
The exception reads "Could not find workload graph-data-generator."

### Description of Problem, Any Other Info
I can't actually get this workload to run or generate any data (the Data Generator - Graph Generator example on the site). The exception reads "Could not find workload graph-data-generator."

I see it called a "legacy" workload in this open issue...is it possible there's a conflict with particular updates? Maybe it's my newer version of Spark (2.2.1)?

**Comment by ecurtin** [comment]
@JDetwiler15

**Comment by ecurtin** [comment]
I was not able to reproduce the issue using Spark 2.1.1 running with master local[*] and this configuration file:

```
spark-bench = {
  spark-submit-config = [{
    workload-suites = [
      {
        descr = "Simple graph data generation test"
        benchmark-output = "console"
        workloads = [
          {
            name = "graph-data-generator"
            vertices = 100
            // Change this to hdfs:///tmp/one-hundred-vertex-graph.txt as appropriate for your system
            output = "/tmp/one-hundred-vertex-graph.txt"
          }
        ]
      }
    ]
  }]
}
```
Results: 
```
$ head /tmp/one-hundred-vertex-graph.txt/*
==> /tmp/one-hundred-vertex-graph.txt/_SUCCESS <==

==> /tmp/one-hundred-vertex-graph.txt/part-00000 <==
0 7
0 11
0 27
0 39
0 44
0 57
0 79
0 95
1 21
1 24

==> /tmp/one-hundred-vertex-graph.txt/part-00001 <==
50 0
50 0
50 8
50 13
50 16
50 18
50 19
50 20
50 21
50 22
```

@JDetwiler15 your hypothesis about Spark versions may be correct, I'll investigate with 2.2.1 shortly. In the meantime, a few questions for you:

1. What version of Spark-Bench are you running? (never a bad idea to try updating to the latest!)
2. May I see the configuration file you were using that threw the exception?

**Comment by ecurtin** [comment]
@JDetwiler15 I was also able to generate graph data locally using Spark 2.2.1 with the following config file, so it would appear that Spark version is not the issue.

```
spark-bench = {
  spark-submit-config = [{
    spark-home = "/opt/spark-2.2.1-bin-hadoop2.7/"
    workload-suites = [
      {
        descr = "Simple graph data generation test"
        benchmark-output = "console"
        workloads = [
          {
            name = "graph-data-generator"
            vertices = 100
            // Change this to hdfs:///tmp/one-hundred-vertex-graph.txt as appropriate for your system
            output = "/tmp/one-hundred-vertex-graph.txt"
          }
        ]
      }
    ]
  }]
}

```

**Comment by JDetwiler15** [comment]
Sorry for the delay, I'm using Spark Bench version 2.1.1_0.2.2, with this workload configuration

    spark-bench = {
        spark-submit-config = [{
            spark-home = "~/spark-2.2.1-bin-hadoop2.7/"
            workload-suites = [{
                descr = "Data Generator - Graph Generator"
                parallel = true
                repeat = 1
                benchmark-output = "console"
    
                workloads = [{
                    name = "graph-data-generator"
                    vertices = 1000000
                    output = "./one-million-vertex-graph.txt"
                }]
            }]
        }]
    }

The stack trace of the error looks like this:

    Exception in thread "main" com.ibm.sparktc.sparkbench.utils.SparkBenchException: Could not find workload graph-data-generator
	at com.ibm.sparktc.sparkbench.workload.ConfigCreator$.mapToConf(ConfigCreator.scala:41)
	at com.ibm.sparktc.sparkbench.workload.SuiteKickoff$$anonfun$1.apply(SuiteKickoff.scala:45)
	at com.ibm.sparktc.sparkbench.workload.SuiteKickoff$$anonfun$1.apply(SuiteKickoff.scala:45)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.immutable.List.map(List.scala:285)
	at com.ibm.sparktc.sparkbench.workload.SuiteKickoff$.run(SuiteKickoff.scala:45)
	at com.ibm.sparktc.sparkbench.workload.MultipleSuiteKickoff$$anonfun$com$ibm$sparktc$sparkbench$workload$MultipleSuiteKickoff$$runSuitesSerially$1.apply(MultipleSuiteKickoff.scala:24)
	at com.ibm.sparktc.sparkbench.workload.MultipleSuiteKickoff$$anonfun$com$ibm$sparktc$sparkbench$workload$MultipleSuiteKickoff$$runSuitesSerially$1.apply(MultipleSuiteKickoff.scala:24)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at com.ibm.sparktc.sparkbench.workload.MultipleSuiteKickoff$.com$ibm$sparktc$sparkbench$workload$MultipleSuiteKickoff$$runSuitesSerially(MultipleSuiteKickoff.scala:24)
	at com.ibm.sparktc.sparkbench.workload.MultipleSuiteKickoff$$anonfun$run$1.apply(MultipleSuiteKickoff.scala:13)
	at com.ibm.sparktc.sparkbench.workload.MultipleSuiteKickoff$$anonfun$run$1.apply(MultipleSuiteKickoff.scala:10)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at com.ibm.sparktc.sparkbench.workload.MultipleSuiteKickoff$.run(MultipleSuiteKickoff.scala:10)
	at com.ibm.sparktc.sparkbench.cli.CLIKickoff$.main(CLIKickoff.scala:16)
	at com.ibm.sparktc.sparkbench.cli.CLIKickoff.main(CLIKickoff.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:755)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:180)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:205)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:119)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
    Caused by: java.lang.Exception
	at com.ibm.sparktc.sparkbench.utils.SparkBenchException$.apply$default$2(SparkBenchException.scala:5)
	... 28 more

I also happened to have Spark 2.2.0 nearby, so I checked it too and I got the same error. I've read over my config file numerous times and don't see any silly syntax mistakes, so my best guess is still conflicting version numbers.

**Comment by JDetwiler15** [comment]
I played around with it some more and found my error. It was that I had the output as "./one-million-vertex-graph.txt", changing it to an absolute path like "/tmp/one-million-vertex-graph.txt" resolved it. Sorry for the false bug, and thanks for your help!

**Comment by ecurtin** [comment]
@JDetwiler15 that's great to hear! Just a note for cluster usage, it's usually better to use HDFS or object storage for the inputs and outputs since files with local paths will be written locally on each of the executors.

That's a good point about the one million vertex example. I'll make a note to change the example to a more default-friendly size.
