### ISSUE TITLE
using deploy-mode cluster fails with com.typesafe.config.Conf                     igException$Parse: String: 1: Expecting close brace } or a comma, got end of file)

### ISSUE THREAD

**Issue by lagishtein** [SparkTC/spark-bench#167]
### Spark-Bench version (version number, tag, or git commit hash)
0.3.0
### Details of your cluster setup (Spark version, Standalone/Yarn/Local/Etc)
2.2.1 ( hdp 2.6.3) yarn
### Scala version on your cluster
2.11
### Your exact configuration file (with system details anonymized for security)
[benchmark-conf.txt](https://github.com/SparkTC/spark-bench/files/1839313/benchmark-conf.txt)

### Relevant stacktrace
[benchmark-fail-deploy-mode.txt](https://github.com/SparkTC/spark-bench/files/1839304/benchmark-fail-deploy-mode.txt)

Last 4096 bytes of stderr :
odAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$3.run(ApplicationMaster.scala:646)
18/03/22 17:18:45 INFO ApplicationMaster: Final app status: FAILED, exitCode: 15, (reason: User class threw exception: com.typesafe.config.Conf                     igException$Parse: String: 1: Expecting close brace } or a comma, got end of file)
18/03/22 17:18:45 ERROR ApplicationMaster: Uncaught exception:
org.apache.spark.SparkException: Exception thrown in awaitResult:
        at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:205)
        at org.apache.spark.deploy.yarn.ApplicationMaster.runDriver(ApplicationMaster.scala:423)
        at org.apache.spark.deploy.yarn.ApplicationMaster.run(ApplicationMaster.scala:282)
        at org.apache.spark.deploy.yarn.ApplicationMaster$$anonfun$main$1.apply$mcV$sp(ApplicationMaster.scala:768)
        at org.apache.spark.deploy.SparkHadoopUtil$$anon$2.run(SparkHadoopUtil.scala:67)
        at org.apache.spark.deploy.SparkHadoopUtil$$anon$2.run(SparkHadoopUtil.scala:66)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1866)
        at org.apache.spark.deploy.SparkHadoopUtil.runAsSparkUser(SparkHadoopUtil.scala:66)
        at org.apache.spark.deploy.yarn.ApplicationMaster$.main(ApplicationMaster.scala:766)
        at org.apache.spark.deploy.yarn.ApplicationMaster.main(ApplicationMaster.scala)
Caused by: com.typesafe.config.ConfigException$Parse: String: 1: Expecting close brace } or a comma, got end of file

see full stacktrace in benchmar-fail-deploy-mode.txt

**Comment by shotreal** [comment]
I am also experiencing this issue when running the example configuration.
I guess this is probably due to some misconfiguration / typo. 

Have you solved the problem / found the reason? This is very annoying.
