### ISSUE TITLE
ssh & class name problem

### ISSUE THREAD

**Issue by abedad** [SparkTC/spark-bench#7]
when running(standalone): "spark-bench-master/Streaming/bin$ ./run.sh TwitterAlgebirdCMS"
stack dropped:

du: cannot access ‘/home/abed/SparkBench/LinearRegression/Input’: No such file or directory
========== running streaming-TwitterAlgebirdCMS benchmark ==========
rm: cannot remove ‘/home/abed/SparkBench/streaming/Output’: No such file or directory
date purged on 
ssh: connect to host abed-virtualbox port 22: Connection refused
Warning: Ignoring non-spark config property: twitter4j.oauth.accessTokenSecret=oopf1YVLvqOgTMn46i72go1Ok84KS3MiZ5QtS6zJybIf2
Warning: Ignoring non-spark config property: twitter4j.oauth.consumerSecret=4oiAOoK6UA1q3IW24Mp2gyjhljbw5tPvbzVKvtOYLp
Warning: Ignoring non-spark config property: twitter4j.oauth.accessToken=18195366-xRzwB9QiTlX1z1av4LQ3QWGvsGIhTiQcLzEXUSMGb
Warning: Ignoring non-spark config property: twitter4j.oauth.consumerKey=cD3wXjfmKbmMy43KP3f2lmcgK
Warning: Local jar /home/abed/spark-1.5.2-bin-hadoop2.4/examples/target/scala-2.10/spark-examples-1.5.1-hadoop2.3.0.jar does not exist, skipping.
java.lang.ClassNotFoundException: org.apache.spark.examples.streaming.TwitterAlgebirdCMS
    at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:274)
    at org.apache.spark.util.Utils$.classForName(Utils.scala:173)
    at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:641)
    at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:180)
    at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:205)
    at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:120)
    at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
./run.sh: line 100: get_config_fields: command not found

**Comment by ecurtin** [comment]
Thanks for submitting an issue to spark-bench!

Spark-bench has recently gone through a major rewrite, and it looks like this issue is targeted towards the legacy version. 

If you'd like to reopen this issue for examination against the legacy branch feel free, but I am going to close this for now due to inactivity.
